-- Insert parent user first
INSERT INTO USERS (ID, EMAIL, NAME)
VALUES (1, 'srikanth@gmail.com', 'Srikanth');

-- Insert budgets for that user
INSERT INTO BUDGETS (ID, USER_ID, CATEGORY, MONTHLY_LIMIT)
VALUES (100, 1, 'FOOD', 5000.00);

INSERT INTO BUDGETS (ID, USER_ID, CATEGORY, MONTHLY_LIMIT)
VALUES (101, 1, 'TRAVEL', 12000.00);

INSERT INTO BUDGETS (ID, USER_ID, CATEGORY, MONTHLY_LIMIT)
VALUES (102, 1, 'SHOPPING', 8000.00);