spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:postgresql://${DB_HOST_NAME}/finance-tracker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/3be72ede-1008-4e37-88c9-f0192dd1e339/v2.0


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8080