name: Deploy UI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: aws-cloud
        type: choice
        options:
          - aws-cloud

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-2
      S3_BUCKET: finance-ui

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci
        working-directory: finance-ui

      - name: Build Angular
        run: npm run build --configuration production
        working-directory: finance-ui

      - name: Sync to S3
        run: |
          aws s3 sync finance-ui/dist/ s3://$S3_BUCKET --delete