name: Terraform Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: aws-cloud
        type: choice
        options:
          - aws-cloud

      action:
        description: "Terraform action"
        required: true
        type: choice
        default: plan
        options:
          - plan
          - apply
          - destroy
          - validate
          - refresh
          - state-list
          - output
          - custom

      custom_args:
        description: "Custom terraform args (used only when action=custom)"
        required: false
env:
  region: us-east-2
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    defaults:
      run:
        working-directory: infra

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # -------------------------
      # PLAN
      # -------------------------
      - name: Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: |
          terraform plan \
            -var-file=tfvars/${{ github.event.inputs.environment }}.tfvars

      # -------------------------
      # APPLY
      # -------------------------
      - name: Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform apply -auto-approve \
            -var-file=tfvars/${{ github.event.inputs.environment }}.tfvars

      # -------------------------
      # DESTROY
      # -------------------------
      - name: Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          terraform destroy -auto-approve \
            -var-file=tfvars/${{ github.event.inputs.environment }}.tfvars

      # -------------------------
      # VALIDATE
      # -------------------------
      - name: Validate
        if: ${{ github.event.inputs.action == 'validate' }}
        run: terraform validate

      # -------------------------
      # REFRESH
      # -------------------------
      - name: Refresh
        if: ${{ github.event.inputs.action == 'refresh' }}
        run: |
          terraform refresh \
            -var-file=tfvars/${{ github.event.inputs.environment }}.tfvars

      # -------------------------
      # STATE LIST (IMPORTANT)
      # -------------------------
      - name: State List
        if: ${{ github.event.inputs.action == 'state-list' }}
        run: terraform state list

      # -------------------------
      # OUTPUT
      # -------------------------
      - name: Terraform Output
        if: ${{ github.event.inputs.action == 'output' }}
        run: terraform output

      # -------------------------
      # CUSTOM COMMAND MODE
      # -------------------------
      - name: Custom Terraform Command
        if: ${{ github.event.inputs.action == 'custom' }}
        run: terraform ${{ github.event.inputs.custom_args }}